### ISSUE TITLE
Running v1.13.12 against iSM

### ISSUE THREAD

**Issue by p3lim** [galexrt/dellhw_exporter#121]
Hey,

Nice little exporter, tried running it against iSM 5.3.0 / iSM OSC 7.3.0 on iDRAC 9 v7.00.00.00, and here are my findings:

- immediately got an error when starting:
   - `/usr/libexec/instsvcdrv-helper: line 519: lsmod: command not found` x5
   - exporter still starts
- `dell_hw_chassis_temps` all report `0`, but `dell_hw_chassis_temps_reading` have values, unsure what the difference between these two are

All other metrics seems to work fine! :+1:

**Comment by galexrt** [comment]
The `lsmod: command not found` can be ignored, as the Dell OMS service startup script tries to check if the necessary modules are there/need to `modprobe`d.

I'll take a look at the `dell_hw_chassis_temps` metric reporting `0` soon.

**Comment by galexrt** [comment]
@eugene-marchanka The `dell_hw_chassis_temps` metric is reporting the "status" as a number, e.g., `0` = "OK", see for a section that explains the status numbers https://github.com/galexrt/dellhw_exporter/blob/main/docs/metrics.md#what-do-the-metrics-mean
(The docs site is currently broken which I'm looking into soon)

The `chassis_temps_reading` is the one that reports the actual temperature reading.

**Comment by eugene-marchanka** [comment]
> @eugene-marchanka The `dell_hw_chassis_temps` metric is reporting the "status" as a number, e.g., `0` = "OK", see for a section that explains the status numbers https://github.com/galexrt/dellhw_exporter/blob/main/docs/metrics.md#what-do-the-metrics-mean (The docs site is currently broken which I'm looking into soon)
> 
> The `chassis_temps_reading` is the one that reports the actual temperature reading.

Thanks @galexrt !
I successfully installed `dellhw_exporter` to our qa/dev environments and ready to roll it out to prod systems 👍🏻

**Comment by galexrt** [comment]
Great to hear!

I think as the issue itself stands, the questions/points have been answered so I'm going to close the issue.

I might revisit the issue in the future to add the `dell_hw_chassis_temps` question to a FAQ section.
