### ISSUE TITLE
Feature Request: Add meta information about the dellhw_exporter version itself to the metrics

### ISSUE THREAD

**Issue by dmaphy** [galexrt/dellhw_exporter#125]
To ease the analysis of which version of the dellhw_exporter is rolled out in an IT landscape it would be neat if the dellhw_exporter would contain a metric about it's own version.

**Comment by galexrt** [comment]
I have added a new metric called `dell_hw_exporter_version` that I will include in an upcoming minor update in the next 2-3 days.

**Comment by galexrt** [comment]
@dmaphy I have just created the [`v1.13.13` release](https://github.com/galexrt/dellhw_exporter/releases/tag/v1.13.13) which contains this new metric.
