### ISSUE TITLE
Export omreport chassis info metric(s)

### ISSUE THREAD

**Issue by B0go** [galexrt/dellhw_exporter#135]
Hi

Recently a need to display and map the Chassis models of all our Dell hardware arose, which made me think that we could export this kind of data out of omreport into one or two metrics to automatically visualize details on all of them. Here is an example output of the command:

```
$ omreport chassis info
Chassis Information

Index                                    : 0
Chassis Name                             : Main System Chassis
Host Name                                : hostname
iDRAC9 Version                           : x.x.x.x (Build 32)
Lifecycle Controller Version             : x.x.x.00
Chassis Model                            : PowerEdge RXXXX
Chassis Lock                             : Present
Chassis Service Tag                      : {tag}
Express Service Code                     : {code}
Chassis Asset Tag                        : Unknown
Flash chassis identify LED state         : Off
Flash chassis identify LED timeout value : 300
```

Is that something that have been considered already?

**Comment by galexrt** [comment]
I can look into introducing a collector for it, that is by default disabled though. I would need to build it upon the #134 PR which is not tested on a live server yet, so I would propose that I'll look into adding a collector to that PR and creating a version that you can build/test, to verify that the rewrite works as expected on a live server.

What do you think? :smile:

**Comment by B0go** [comment]
I might be able to help with the testing, yeah! Here is the command output:

```
bogo@kvm-120:~$ omreport chassis info -fmt ssv
Chassis Information

Index;0
Chassis Name;Main System Chassis
Host Name;hostname
iDRAC9 Version;5.x.x.x (Build x)
Lifecycle Controller Version;5.x.x.x
Chassis Model;PowerEdge Rxxxx
Chassis Lock;Present
Chassis Service Tag;123XXX
Express Service Code;123456
Chassis Asset Tag;Unknown
Flash chassis identify LED state;Off
Flash chassis identify LED timeout value;300
```

**Comment by galexrt** [comment]
@B0go I have added such a metric to my PR #134, what would be the best way for you to test it? Can you compile it, or should I look into creating a release candidate (that binaries and container images will be easily available) that includes the rework and the chassis info metric?

**Comment by B0go** [comment]
Great @galexrt, I will reserve some time this week or the next to test it. Thanks

**Comment by B0go** [comment]
Hi @galexrt, sorry for the delay. I should test it this week.

**Comment by galexrt** [comment]
I have release `2.0.0-rc.1` https://github.com/galexrt/dellhw_exporter/releases/tag/v2.0.0-rc.1

If you have a chance to test the release candidate and find any issues with it, please let me know via a new issue.

Closing this issue as the feature is implemented now and just waiting for a full release.
