### ISSUE TITLE
Predictive failure

### ISSUE THREAD

**Issue by cristianleontecsp** [galexrt/dellhw_exporter#14]
Hi All,

how about a metric for predictive failure of the disks?

Cheers

**Comment by galexrt** [comment]
@cristianleontecsp Does Dell OMSA have this functionality?

**Comment by neuro42** [comment]
Yes.  Specifically, in StoragePdisk, fields[9] will be a "Yes" or "No" value indicating that the disk is predicted to fail.  I'm not sure if you want to add a new overall value for that (3?) or return the same value as non-critical (2)

Failure Predicted               : No

**Comment by galexrt** [comment]
So if that info is provided by `omreport` I could probably add that as an additional metric somehow.

I'll check the coming days to check if that is easily doable.

**Comment by galexrt** [comment]
New release 1.10.0 is pushed and currently being built, let me know if the new metric works well for you.

**Comment by neuro42** [comment]
Just had a disk go to predictive failure which allowed this to be tested beyond a solid string of 0s.  Working as expected.

**Comment by galexrt** [comment]
@neuro42 good to hear, thanks for letting me know!
