### ISSUE TITLE
Is it working with OMSA 9.1? 

### ISSUE THREAD

**Issue by cloud-rocket** [galexrt/dellhw_exporter#17]
tnx

**Comment by galexrt** [comment]
@cloud-rocket It could. Try it out and let me know.
Though if you are using the Docker container version, it shouldn't matter at all, as the OMSA version inside the container is used.

**Comment by galexrt** [comment]
As written if you use the container version the in-container version of OMSA is used.
If you are using the binary, then please try it out and report here if it was working with the OMSA version of the host.

Closing as no response.

**Comment by cloud-rocket** [comment]
Sorry for a delay - seems to be working!
Tnx
