### ISSUE TITLE
Build fails with: case-insensitive import collision: "github.com/sirupsen/logrus"

### ISSUE THREAD

**Issue by dougszumski** [galexrt/dellhw_exporter#21]
The following command fails to build:

```
curl -sSL -o /tmp/dellhw_exporter.tar.gz https://github.com/galexrt/dellhw_exporter/archive/v1.3.5.tar.gz && mkdir /tmp/dellhw_exporter     && tar --strip 1 -xvf /tmp/dellhw_exporter.tar.gz
 -C /tmp/dellhw_exporter && cd /tmp/dellhw_exporter && go get -d ./... && make build
```

With the error:

```
package github.com/sirupsen/logrus: case-insensitive import collision: "github.com/sirupsen/logrus" and "github.com/Sirupsen/logrus"
```

This appears to be due to the author of this lib renaming the account.

If I run the following before `go get`, I can build without issue:

```
find . -type f -print0 | xargs -0 sed -i 's/Sirupsen/sirupsen/g'
```

Should we update the case to reflect the upstream rename?

Thanks for sharing your work.

**Comment by galexrt** [comment]
@dougszumski Yes, changing it to `github.com/sirupsen/logrus` sounds good as long as it is not done over the `vendor/` directory.

Would you be up to create a PR to fix that?
