### ISSUE TITLE
metrics for the duration of the omreport calls and tunable timeouts

### ISSUE THREAD

**Issue by juliantaylor** [galexrt/dellhw_exporter#26]
the omreport commands seem to take varying amounts of time, on dell R640 they even sometimes exceed the 10 second timeouts

it might be interesting to have metrics about how long each command takes to better tune the timeouts of the commands.

**Comment by galexrt** [comment]
@juliantaylor There should already be metrics about the duration per collector, not "directly" per omreport calls but for the whole, e.g., `omreport chassis ...` call and output parsing.

Could you please try out this newly added flag for the `omreport` command timeout?
```console
$ dellhw_exporter --help
Usage: dellhw_exporter [OPTION]...
  -collectors.cmd-timeout int
    	Command execution timeout for omreport (default 15)
```
The flag is available on latest `master` and the soon to available `v1.4.0` Docker tag (currently being built and pushed).
