### ISSUE TITLE
make: /bin/promu: Command not found

### ISSUE THREAD

**Issue by mozai** [galexrt/dellhw_exporter#30]
I believe 'promu' is missing from the list of dependencies in the README.md .

```
$ git clone https://github.com/galexrt/dellhw_exporter.git
$ cd dellhw_exporter
$ make
...
make: /bin/promu: Command not found
make: *** [Makefile:25: build] Error 127
```

**Comment by galexrt** [comment]
Please post the whole output of the `make` run.
`promu` is fetched during the build target / process.

**Comment by mozai** [comment]
Nevermind, it was a bad $GOPATH envvar.

**Comment by mozai** [comment]
oddly, the "go get -u github.com/prometheus/promu" did put it in the right place, but later in the Makefile "${GOPATH}/bin/promu" turned into "/bin/promu" so of course it didn't find promu.
