### ISSUE TITLE
manual setup

### ISSUE THREAD

**Issue by andrewm659** [galexrt/dellhw_exporter#38]
So i'm trying to set this up manually but I don't see what port it runs on or what I need to put in my prometheus configuration so ti scrapes it.  Can you help with this and can you update the README.md to provide this in the future?

**Comment by andrewm659** [comment]
nm.

**Comment by galexrt** [comment]
I have added some documentation around running the dellhw_exporter without Docker and also an example static Prometheus job config to the `README.md` file.

**Comment by andrewm659** [comment]
Also was this intended to run on a physical server running linux i'm guessing?

**Comment by galexrt** [comment]
Yes, you can run it on a Linux server directly. The Docker image "packaging" is just for easy for people running, e.g., Docker and / or Kubernetes.
