### ISSUE TITLE
Minor trouble with updated build routines (promu-related)

### ISSUE THREAD

**Issue by sfudeus** [galexrt/dellhw_exporter#42]
Hi Alex, 

while trying to use your updated build setup with `promu` I stumbled over some minor issues which break our builds. 

a) `promu` is referenced  as `$(PROMU)` in the Makefile, which is only set to `promu`, assuming that it lives in the path. I suggest to use either the location where you put it (`$(FIRST_GOPATH)/bin/promu`) or set that as variable `PROMU`

b) `Makefile` assumes `PREFIX` being set when calling `promu --prefix $(PREFIX)`, but `PREFIX` might not be set. I suggest to add `--prefix $(PREFIX)` only when `PREFIX` is set. 

Cheers,
Stephan

**Comment by galexrt** [comment]
@sfudeus Hi Stephan,

1. Yeah, makes sense. I have switched it to use the downloaded promu binary path.
2. The `CWD` variable should have been used there, instead of the `PREFIX`.

Will push a new release in a bit that includes those fixes.

Please let me know if that resolves the issues found.

**Comment by sfudeus** [comment]
thx, looks good so far
