### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by poblahblahblah** [galexrt/dellhw_exporter#55]
Hello,

Can a new release get cut? We'd like to run this as a windows service (#54) and pull the binary from an official release.

Thanks for the project, and thank you in advance!

**Comment by galexrt** [comment]
v1.8.0 has been released, see https://github.com/galexrt/dellhw_exporter/releases/tag/v1.8.0

**Comment by poblahblahblah** [comment]
Thank you so much!
