### ISSUE TITLE
OMSA running in container

### ISSUE THREAD

**Issue by miroslavmasaryk3221** [galexrt/dellhw_exporter#64]
Hello, @juliantaylor @galexrt @sfudeus @jddggh @kyle-williams-1 

does it support OMSA also running in container ? e.g. https://github.com/ShaneMcC/docker-omsa

**Comment by galexrt** [comment]
@miroslavmasaryk3221 It might work, you should be able to check if the exporter reports anything or try running `omreport` in the `dellhw_exporter` container.

**Comment by miroslavmasaryk3221** [comment]
Yes it works, thanks,

**Comment by galexrt** [comment]
@miroslavmasaryk3221 Can you run `omreport chassis bios` and `omreport chassis firmware` in the dellhw_exporter container and also in the docker OMSA container?
