### ISSUE TITLE
Add raid layout for vdisk

### ISSUE THREAD

**Issue by zoonage** [galexrt/dellhw_exporter#8]
use case: 
Sometimes we don't care about a broken disk because of the a specific RAID setup, it would be nice for us to be able to use the RAID controller metric to alert on.

proposition:
I was thinking something like;

    dell_hw_storage_vdisk_raid{vdisk="0"} 10 // RAID 10
    dell_hw_storage_vdisk_raid{vdisk="1"} 5 // RAID 5

**Comment by galexrt** [comment]
@zoonage There is a way to check if there is a broken disk without knowing which RAID is used in the system. I send you the Prometheus query when I find it.
But yes having "more" metrics about more than just state would be good.

**Comment by zoonage** [comment]
I was thinking more along the lines of alerting rules, I'll start work on it and submit a pull request

**Comment by galexrt** [comment]
@zoonage Thanks! With Prometheus query I meant an alert rule for alerting on failed/broken disks.

**Comment by zoonage** [comment]
^ badly explained

There might be cases where if there were X failed disks then that would be fine in a particular raid setup but not another one

**Comment by galexrt** [comment]
I understand now. Yes, a metric like `dell_hw_storage_vdisk_raid` would be useful.

If you need help with that, please let me know!

**Comment by galexrt** [comment]
@zoonage Better late than never, a metric named `dell_hw_storage_vdisk_raidlevel` has been added. The new metrics exposes the **VDisk RAID level** as a metric.
