### ISSUE TITLE
Alerts / Graphs

### ISSUE THREAD

**Issue by cleonte** [galexrt/dellhw_exporter#9]
Hi, 

Thanks for this, looks very good! btw, do you have any alerts defined or graphana dashboards?

Cheers

**Comment by galexrt** [comment]
@cleonte I have to look into pushing example alerts and dashboards, as they are made by the company I currently work at. But it shouldn't be a problem of adding them.
I'll let you know when I have added them.

**Comment by cleonte** [comment]
10q

At this point i'm using nagios with some home made scripts for dell :) but would like to  change to prometehus and you dell exporter si cool!

Cheers

**Comment by altitude1326** [comment]
It will be very usefull if you can commit sample grafana dashboard. I’m not an expert but I could try to enrich it.

**Comment by galexrt** [comment]
I finally had the time again, so I pushed a Grafana dashboard and a few Prometheus alert rules, see https://github.com/galexrt/dellhw_exporter/tree/dev/contrib/monitoring.
I will look into merging the changes on `dev` into `master` soon.

Thanks to @dhoeld for creating the Grafana dashboard and the Prometheus alerts initially and the company I work at!

**Comment by cleonte** [comment]
sorry, so sorry, just saw your comment, will try it as soon as i can!

the alerts look cool! cant' wait to try the dashboard!
